### ISSUE TITLE
Custom field data not showing in open chat

### ISSUE THREAD

**Issue by StevenDeBeer** [CodeCabin/wp-live-chat-support#1004]
Custom field data only appears once the chat has been minimised and reopened instead of on intial accepting of chat.
![screen shot 2018-09-17 at 11 16 55 am](https://user-images.githubusercontent.com/41285248/45614980-81fe6500-ba6b-11e8-8d3c-6524e876537d.png)

**Comment by DylanCodeCabin** [comment]
Pro issue -> Closing and relogging now
