### ISSUE TITLE
default styling for "powered by"

### ISSUE THREAD

**Issue by NickDuncanZA** [CodeCabin/wp-live-chat-support#1006]
We need to set default styling for the powered by so things like this dont happen:

![image](https://user-images.githubusercontent.com/16645118/45663993-b32d7280-bb09-11e8-9762-8f813cf0f82b.png)

**Comment by DylanCodeCabin** [comment]
This is a server side change, I will roll this out within this week

**Comment by DylanCodeCabin** [comment]
Sorted! 💃
