### ISSUE TITLE
COMING SOON in Readme - Needs updating urgently

### ISSUE THREAD

**Issue by NickDuncanZA** [CodeCabin/wp-live-chat-support#1037]
I was informed by a customer that his customer wanted to get refunded because of this:

![image](https://user-images.githubusercontent.com/16645118/50087825-faf78f00-0209-11e9-84ff-697ce2882cf0.png)

Can we update the readme to include the mobile apps and put a fresh set of items for the Coming Soon section please

**Comment by DylanCodeCabin** [comment]
8.0.21 Going live now. This resolved readme issues. I will update the doc as soon as possible.

**Comment by DylanCodeCabin** [comment]
Resolved
