### ISSUE TITLE
100% translated files for Slovenian language

### ISSUE THREAD

**Issue by dylank6169** [CodeCabin/wp-live-chat-support#1044]
Here are the language files for the 'Slovenian' language done by a client and is 100% translated. PO and MO files are included in this zipped file
[slovenian.zip](https://github.com/CodeCabin/wp-live-chat-support/files/2796161/slovenian.zip)

**Comment by DylanCodeCabin** [comment]
@dylanjkotze Can you please confirm who should get credit for this?

**Comment by dylank6169** [comment]
HI Dylan,

It is Žarko Germek
https://bleeper.io/app/inbox/?action=messages#qox_sfohv_1548351064440

**Comment by DylanCodeCabin** [comment]
Thank you!

Added to 8.0.24 release
