### ISSUE TITLE
Google Ads blocked my website...

### ISSUE THREAD

**Issue by Auto-Reverse** [CodeCabin/wp-live-chat-support#1048]
Hi everyone!

My googleads account has been blocked by google. It has happened twice, in the first week of January 2019 and now, in the first week of February.

This is my website:
https://www.auto-reverse.com

The reason is that my website may contain malware, that Google has identified in theese links:
https://www.auto-reverse.comhttps//c0.wp.com/c/5.0.3/wp-includes/js/jquery/ui/tabs.min.js
https://www.auto-reverse.comhttps//c0.wp.com/c/5.0.3/wp-includes/js/shortcode.min.js
https://www.auto-reverse.comhttps//c0.wp.com/c/5.0.3/wp-includes/js/thickbox/thickbox.js

I have been told to make a caption of the tests by Searchconsole and Transparency, witch revealed  no major problem. 

I am not very good but I suppose theese are J Queries, but they doesn't seem to be used in my website. Does any of you have ever encountered that before?

I don't know what to do to get back my ads????

**Comment by DylanCodeCabin** [comment]
Hi @Auto-Reverse,

I had a look at your site and it does not appear to be loading our chat plugin: https://wp-livechat.com/

Additionally, these files are not files we load within the WP Live Chat Support Plugin. 

WP Live Chat Support is a plugin which allows you to serve a chat box on your website to allow visitors to chat with you. 

I believe you may be looking for general WordPress support. Unfortunately, we do not offer general support for WordPress. 

I would recommend reaching out to your web developer, or alternatively your host to provide you with further assistance.
