### ISSUE TITLE
Company name auto adds backslash in Privacy section when an apostrophe is added.

### ISSUE THREAD

**Issue by StevenDeBeer** [CodeCabin/wp-live-chat-support#1049]
https://bleeper.io/app/ticket_uploads/8e7571b69ed079c33a3c1574d8a35253/7cd5651266311a9a.png

When saving multiple times multiple backslashes are added.

**Comment by DylanCodeCabin** [comment]
![image](https://user-images.githubusercontent.com/16894783/53412431-09b0ae00-39d2-11e9-8982-1ceac6e93a6f.png)
Fixed in 8.0.24 Release
