### ISSUE TITLE
Basic version advertises Pro for $19.95 instead of $39.95

### ISSUE THREAD

**Issue by JarrydLong** [CodeCabin/wp-live-chat-support#110]

**Comment by NickDuncanZA** [comment]
Please confirm where?

**Comment by JarrydLong** [comment]
Came from an outdated version. Sorry about that.

**Comment by JarrydLong** [comment]
Current Basic version does not display a price, however all translations still contain a $19.95 price tag in them. 

When using languages such as German, it changes the promo message to one with a price in it for some reason. Language files just need to be edited have have the price removed from all of them.

**Comment by JarrydLong** [comment]
Basic version in English

![image](https://cloud.githubusercontent.com/assets/8989542/18506381/28305858-7a6c-11e6-9a3b-ca25c72fb00a.png)

Basic version in German

![image](https://cloud.githubusercontent.com/assets/8989542/18506445/6d6d41b0-7a6c-11e6-95e8-f4ec02c3d132.png)

Pricing values need to be removed in all language files as well to ensure this doesn't occur

**Comment by DylanCodeCabin** [comment]
All calls to this have been removed in language files. Should now be resolved.
