### ISSUE TITLE
Cannot view individual chat history conversations when using Cloud Server Extension

### ISSUE THREAD

**Issue by JarrydLong** [CodeCabin/wp-live-chat-support#130]
'This chat has already been answered. Please close the chat window' is displayed when trying to view a single chat on Cloud Server Extension

**Comment by JarrydLong** [comment]
Has anyone still experienced issues with this? I can't seem to replicate it on my side locally

**Comment by NickDuncanZA** [comment]
Havent tested but I'm sure we fixed this with the last set of cloud issues

**Comment by JarrydLong** [comment]
I'm going to close this issue then, thank you @NickDuncanZA
