### ISSUE TITLE
Agent and visitor names don't display on Cloud Server Extension

### ISSUE THREAD

**Issue by JarrydLong** [CodeCabin/wp-live-chat-support#131]
User and agent names don't come through in chats when using the Cloud Server Extension

**Comment by JarekCodeCabin** [comment]
I've tested this with the Cloud Server Extension and agent name display both on admin and visitor side. The visitor name don't display. Here are the screenshots:

![cloud-admin-chat](https://cloud.githubusercontent.com/assets/25925938/24410527/901e13dc-13d3-11e7-8858-fdcf2af13e03.jpg)

![cloud-visitor-chat](https://cloud.githubusercontent.com/assets/25925938/24410544/98ccee18-13d3-11e7-997f-0ca636ac0a94.jpg)

**Comment by JarekCodeCabin** [comment]
Small update. Visitor name also display. Screenshots:

![visitor-chat](https://cloud.githubusercontent.com/assets/25925938/24460837/c15521f8-149f-11e7-8ffe-79af6e01eee1.jpg)

![admin-chat](https://cloud.githubusercontent.com/assets/25925938/24460844/c5608c88-149f-11e7-887a-6408ea6d4207.jpg)
