### ISSUE TITLE
Conflict with Responsive Lightbox Lite

### ISSUE THREAD

**Issue by JarrydLong** [CodeCabin/wp-live-chat-support#137]
When Responsive Lightbox Lite, the enter key doesn't send any messages through the chat. 

Reported in WP Forum topic https://wordpress.org/support/topic/incompatiblity-responsive-light-box-with-wp-live-chat/

**Comment by JarekCodeCabin** [comment]
Fix the bug in this commit: https://github.com/CodeCabin/wp-live-chat-support/commit/9e3e23fbcf540a7fcb69f5443c5e34c6591721f7
I'm not sure this is the best way to resolve it but nivoLightbox disable all keyup events on body so we need to overrride this in some way

**Comment by DylanCodeCabin** [comment]
Nicely done @JarekCodeCabin Thank you!
