### ISSUE TITLE
Plugin breaks when using "WP Fastest Cache" and "Combine JS" enabled

### ISSUE THREAD

**Issue by CodeCabinSA** [CodeCabin/wp-live-chat-support#147]
Ticket 32424

**Comment by DylanCodeCabin** [comment]
@NickDuncanZA It appears WP Fastest Cache does not have any hooks for their exclude rule set. We manually pull the option, add to it and resave it but this is very intrusive. Additionally, this setting basically alters the htaccess files, so I would think we should stay away from this in our case.

That said, we could simply document the process properly in our docs for people setting up WP Fastest Cache?

**Comment by NickDuncanZA** [comment]
Documentation sounds like a good plan @DylanCodeCabin

**Comment by DylanCodeCabin** [comment]
Great-> Closing this now, and notifying the docs lead
