### ISSUE TITLE
In chat window, the avatar icons are cut of at right when there are scroll bars (which is most of the time)

### ISSUE THREAD

**Issue by NickDuncanZA** [CodeCabin/wp-live-chat-support#180]
Safari

**Comment by JarrydLong** [comment]
Awaiting feedback. Going to remove this from Version 7's milestone until we can replicate this on a live site and take it from there

**Comment by DylanCodeCabin** [comment]
@JarekCodeCabin Please attempt to reproduce this so that we can either rectify the issue, or remove it from the issues list.

**Comment by JarekCodeCabin** [comment]
I've tested chat window on Chrome, Firefox, Edge. Can't reproduce this one. Everything shows as intended even with scroll bar.

![chat-window](https://cloud.githubusercontent.com/assets/25925938/23951026/3ac9cb92-098d-11e7-9091-c29ae0fc93ea.jpg)
