### ISSUE TITLE
PR: Chat No Longer Opening (Current Build - Commit #240)

### ISSUE THREAD

**Issue by patdumond** [CodeCabin/wp-live-chat-support#241]
While writing documentation I attempted to open a chat and instead of the chat opening the word "ARRAY" appeared where the status messages should be. (
![chat-box-error](https://cloud.githubusercontent.com/assets/9320495/21200224/858e13ec-c214-11e6-9a2a-b0b4d3a0c8dd.png)

I opened the Developer's Console and found these errors:

![console-errors](https://cloud.githubusercontent.com/assets/9320495/21200261/99b2bf08-c214-11e6-8aff-34249d65f659.png)

Please note that this is a test site and I do not have Google Analytics enabled anywhere on the site, including in WP Live Chat Support.

**Comment by JarrydLong** [comment]
@patdumond Please confirm if you used the version that was released on Github or WordPress.org while testing?

**Comment by patdumond** [comment]
GitHub, not WordPress.org.

**Comment by DylanCodeCabin** [comment]
I believe this was fixed by Jarek's last commit. Closing the issue now.
