### ISSUE TITLE
PRIORITY: chat window disappears on click

### ISSUE THREAD

**Issue by NickDuncanZA** [CodeCabin/wp-live-chat-support#247]
This needs some playing around with in order to recreate. It's happened to me once or twice and customers are experiencing this issue as well - mostly when THEY are testing the chat product. This is most likely linked to the cookie.

**Comment by JarrydLong** [comment]
It was found that when the chat status wasn't stored in the cookie, the chat would disappear after being clicked. Version 7.0.01 fixes this and ensures that a cookie is set if one hasn't been already
