### ISSUE TITLE
Node server experiences issues getting a response when posting

### ISSUE THREAD

**Issue by JarrydLong** [CodeCabin/wp-live-chat-support#255]
Found in ticket 5020

Error:  [03-Jan-2017 20:37:57 UTC] PHP Warning: file_get_contents( https://wp-livechat.us-2.evennode.com/system_message): failed to open stream: no suitable wrapper could be found in /home/melon/public_html/wp-content/plugins/wp-live-chat-support/modules/node_server.php on line 78

**Comment by DylanCodeCabin** [comment]
No longer relevant. This entire module was rebuilt -> Also we now have conditional checks to prevent this and fallbacks
