### ISSUE TITLE
History And Chat Transcripts return JSON object

### ISSUE THREAD

**Issue by DylanCodeCabin** [CodeCabin/wp-live-chat-support#257]
I sort of fixed this with a bit of a hack, adding this to the get chat messages function:

`
$msg = $result->msg;

if(strpos($msg, "{") !== FALSE){
$msg = maybe_unserialize($msg);
$msg = $msg['m'];
}
        $msg = stripslashes($msg);
`

**Comment by DylanCodeCabin** [comment]
We need a more robust fix for this as my code above is not sustainable enough in the long run. Perhaps look into building a simple check to determine if a string is serialized data.

**Comment by PerryRylance** [comment]
If you anticipate that it's JSON, I would in the very least write this:

if(strpos($msg, "{") === 0)

If you want to check it's valid JSON, use json_decode, which will return NULL if it's not proper JSON:

if($msg = json_decode($msg) !== null)
	$msg = $msg->{'m'};

**Comment by PerryRylance** [comment]
If that message has been anywhere near a user then absolutely do not use maybe_serialize, which calls serialize, which carries a warning, see http://php.net/manual/en/function.unserialize.php

In short, in some circumstances it's possible for an attacker to inject arbitrary code, the manual recommends that you "Use a safe, standard data interchange format such as JSON (via json_decode() and json_encode()) if you need to pass serialized data to the user."

**Comment by DylanCodeCabin** [comment]
A fix is in place for this in the latest commit based on code above.
