### ISSUE TITLE
Chat History

### ISSUE THREAD

**Issue by VeroniqueSmit** [CodeCabin/wp-live-chat-support#264]
When viewing chat history, you are still able to type in the input field.

**Comment by JarekCodeCabin** [comment]
Tested. Input field in chat history preview is disabled in wplc_u_admin_chat.js line 241:
`document.getElementById('wplc_admin_chatmsg').disabled = true;`

![chat-history-disabled](https://cloud.githubusercontent.com/assets/25925938/23711992/b426936a-0421-11e7-8b36-f653fae61ff6.png)

**Comment by DylanCodeCabin** [comment]
This fix will be released in our next update
