### ISSUE TITLE
iPhone issue when typing (user side)

### ISSUE THREAD

**Issue by NickDuncanZA** [CodeCabin/wp-live-chat-support#265]
> The user on a iphone, has to type the text, then enter, then hit DONE to be able to see the text on the chat window... not very friendly.

Ticket 12156

**Comment by DylanCodeCabin** [comment]
Tested with latest version of iOS -> Tests appear to be be successful. When the user is able to simple press the enter/return button to chat.

I am going to go ahead and close this one for you. 

Tester: @StevenDeBeer
