### ISSUE TITLE
[URGENT] Changes to the welcome message does not take effect when using the cloud server

### ISSUE THREAD

**Issue by NickDuncanZA** [CodeCabin/wp-live-chat-support#267]
The way the welcome message works at the moment is that it is sent as a message when the user initiates the chat. Any delay on the server means the message is delayed to the client. This means that users click on "Start chat", are presented with a blank chat screen and then +-3 seconds later the welcome message is shown.

The bug spoken about in the title is self explanatory. The welcome message is hard coded on the cloud server.

To kill two birds with one stone, we should localize the welcome message and insert it using JS when the chat box is opened and ready for the user to start typing. This will negate both bugs.

**Comment by JarekCodeCabin** [comment]
I tested this issue and "No answer" and "Intro text" from Settings → Styling aren't localized as well.
The same refers to "Admin has closed and ended the chat" string.
I noticed that timestamp is also in english, no matter if "Display a timestamp in the chat window" option is enabled.
