### ISSUE TITLE
Test on MS Edge (URGENT - Needs testing)

### ISSUE THREAD

**Issue by PerryRylance** [CodeCabin/wp-live-chat-support#269]
Reportedly, the chat box is not showing up

**Comment by patdumond** [comment]
Works for me in Edge.
![2017-03-08_9-19-58](https://cloud.githubusercontent.com/assets/9320495/23707468/7ecf29e8-03e0-11e7-9b8c-dc55079678fb.png)

**Comment by JarekCodeCabin** [comment]
Confirmed & tested. It works on Edge

**Comment by DylanCodeCabin** [comment]
Closing this issue as it has been tested by multiple agents and it is working in edge from our tests
