### ISSUE TITLE
Surveys/NimbleSquirrel Issue on HTTPS-Enforced Sites?

### ISSUE THREAD

**Issue by patdumond** [CodeCabin/wp-live-chat-support#274]
While writing documentation on Using Surveys I found that the survey window will not open on my test site. The error message displayed in the console is: `Failed to load resource: net:ERR_INSECURE_RESPONSE`. The listed resource is `nimblesquirrel.js`. The error message is visible in the console at all times, but the major effect is that the survey will not load in the chat box area.

![blank-chat-screen](https://cloud.githubusercontent.com/assets/9320495/23707603/ff9e91b2-03e0-11e7-908e-38f3467897b9.png)
![error-message](https://cloud.githubusercontent.com/assets/9320495/23707602/ff9d01e4-03e0-11e7-9dac-aa81bae6e0ad.png)

**Comment by patdumond** [comment]
I see that I did not mention that SSL is enforced on my test site. Never assume anything, Pat.

**Comment by DylanCodeCabin** [comment]
I believe we need to make some alterations to our output headers on the NimbleSquirrel side. I will have a look at this as soon as I have a chance

**Comment by DylanCodeCabin** [comment]
This one has been completed
