### ISSUE TITLE
Ability to chose between showing the name OR email address fields

### ISSUE THREAD

**Issue by JarrydLong** [CodeCabin/wp-live-chat-support#275]

**Comment by JarekCodeCabin** [comment]
These commits address this issue:
https://github.com/CodeCabin/wp-live-chat-support/commit/4f76ba4d5101da1d3cd80be9d0d372268941a2cd
https://github.com/CodeCabin/wp-live-chat-support-pro/commit/388670489834908d0f38dcf97aeabfe4ab2c4472
