### ISSUE TITLE
Decryption PRO fails due to a bad function call in the basic [PRIORITY]

### ISSUE THREAD

**Issue by DylanCodeCabin** [CodeCabin/wp-live-chat-support#276]
This is being added to the basic as all the function calls originate within the basic. 

Within the ajax-new.php file we need to change this:

`
if(function_exists('wplc_decrypt_msg')){
     $msg = wplc_decrypt_msg($msg);
}
 `      

To this instead:

`
if(function_exists('wplc_encrypt_decrypt_msg')){
    $msg = wplc_encrypt_decrypt_msg($msg);
}
`

This is present in function loops:
- wplc_return_user_chat_messages
- wplc_return_admin_chat_messages

**Comment by JarekCodeCabin** [comment]
This is also present in wplc_return_chat_messages function

**Comment by JarekCodeCabin** [comment]
I changed wplc_decrypt_msg to wplc_encrypt_decrypt_msg.

**Comment by JarrydLong** [comment]
Fixed in Basic version 7.0.06 and Pro 7.0.04
