### ISSUE TITLE
Exclude from home page not respected

### ISSUE THREAD

**Issue by PerryRylance** [CodeCabin/wp-live-chat-support#278]
See https://skinnylaminx.com/ (I've added temporary CSS to solve the problem, but live chat loads even though the setting is checked)

**Comment by DylanCodeCabin** [comment]
This would occur when the home page is not returned as a home page by WordPress. 

We use 'is_home()' to determine this.

**Comment by JarekCodeCabin** [comment]
I moved the bug to Pro version. The exclude chat from homepage is in Pro.
