### ISSUE TITLE
Let agent know user has left chat

### ISSUE THREAD

**Issue by PerryRylance** [CodeCabin/wp-live-chat-support#279]

**Comment by JarrydLong** [comment]
@PerryRylance The chat window will show a message 'Admin has ended the chat'. Are you talking about something else though?

**Comment by DylanCodeCabin** [comment]
@JarrydLong I believe Perry is referring to a second notice that notifies the agent that the user has left. 

For Example: User may have left the chat

**Comment by DylanCodeCabin** [comment]
Node supports this now
