### ISSUE TITLE
Not all Google Analytics events are going through

### ISSUE THREAD

**Issue by JarrydLong** [CodeCabin/wp-live-chat-support#285]
Untested. Reported in a ticket.

**Comment by DylanCodeCabin** [comment]
@JarekCodeCabin Please test and confirm?

**Comment by JarekCodeCabin** [comment]
I've tested the Google Analytics. I haven't noticed any problems. Here are the screenshots:
![events](https://cloud.githubusercontent.com/assets/25925938/24397872/d5af0fae-13a7-11e7-9f55-4d5d76a2369b.png)
![events1](https://cloud.githubusercontent.com/assets/25925938/24397884/d8c36ad2-13a7-11e7-97d8-58926e7c057a.png)
![events2](https://cloud.githubusercontent.com/assets/25925938/24397886/db61ebba-13a7-11e7-93da-5d12ee6d61cc.png)

**Comment by DylanCodeCabin** [comment]
We picked up issues, but they were specific to node users. This is now a new issue, and will be patched in the coming days permanently.
