### ISSUE TITLE
When hidden, ability to set a default visitor name

### ISSUE THREAD

**Issue by JarrydLong** [CodeCabin/wp-live-chat-support#287]

**Comment by JarekCodeCabin** [comment]
These commits:
https://github.com/CodeCabin/wp-live-chat-support/commit/3e2e6ff9b083931d69e4b690548a8e38444a4516
https://github.com/CodeCabin/wp-live-chat-support-pro/commit/315c9f74979c28faebc624ee89a96ff254588bbc
add ability to set a default visitor name. The visitor name will be displayed for all not logged in visitor when require name and email field will be unchecked

**Comment by DylanCodeCabin** [comment]
Correct @JarekCodeCabin worked on this. We are closing this, as this is not a bug, and is a Pro enchancement
