### ISSUE TITLE
Live Chat only works in one window / tab

### ISSUE THREAD

**Issue by PerryRylance** [CodeCabin/wp-live-chat-support#288]
Discovered this a couple of weeks ago, prompted to raise it after some feedback:

- Open live chat admin page
- Open private browsing window, navigate to site frontend
- Open a second tab in private browsing window
- Navigate to site frontend in that second tab
- Live chat icon appears
- Close second tab
- Chat has disappeared in first tab

This isn't ideal if the customer say visits the site, then opens another tab to read some information, then wants to go back to chat on the first tab

**Comment by NickDuncanZA** [comment]
This is intentional.
We only allow the live chat box to show up on one page at a time. If not, the messages will not be sent to both windows, and will get confusing very quickly. To change this requires a massive change in the code and therefore is not feasible.
