### ISSUE TITLE
Invalid selector breaks plugin

### ISSUE THREAD

**Issue by PerryRylance** [CodeCabin/wp-live-chat-support#289]
Putting an invalid selector in "open chat window via" under advanced settings breaks the plugin. I had a chap who perhaps misinterpreted what was supposed to be put in there and had a string ending in an exclamation mark

This field should not allow the user to put in invalid selectors, you could pass the selector to document.querySelector in a try / catch block to test the validity of the selector before allowing the form to submit

**Comment by DylanCodeCabin** [comment]
![image](https://user-images.githubusercontent.com/16894783/42815074-9d189fca-89c6-11e8-8c30-3b08021d8616.png)

This will now be console logged on the front end if, and only if the query is invalid. Thanks to @PerryRylance for the guidance on the try catch, we implemented something similar. 

This will only happen on the front end, this would stop the chat from breaking then. However it would not filter in the settings area. I'd rather not limit things from the backend as I've seen some creative id chaining etc.
