### ISSUE TITLE
[Critical] Chat window isn't following the visitor onto new pages

### ISSUE THREAD

**Issue by JarrydLong** [CodeCabin/wp-live-chat-support#290]
This resulted in a one star review - the client has outlined all the steps followed to re-create the above issue:

https://wordpress.org/support/topic/chat-doesnt-follow-you-if-you-change-page/

**Comment by JarrydLong** [comment]
Tested further:

Locally: Chrome & Firefox - No issues at all. When moving over to a new page, the chat follows. When opening a new page in a new window, the chat follows onto that page and messages come through as expected. 

WPLC Site: Chrome - No issues at all. Firefox - Chat window follows when you move from page to page in the same window. When opening a new window, messages are sent to the first window and not the new window

**Comment by DylanCodeCabin** [comment]
Tested and this is now working as it should. It appears we did fix this, but it was never added to our logs.
