### ISSUE TITLE
Chat session breaks

### ISSUE THREAD

**Issue by PerryRylance** [CodeCabin/wp-live-chat-support#291]
1. Open a chat between customer and agent
2. The agent clicks "end chat"
3. The user stays on the page and later on wants to talk to the agent
4. The user can't send any messages because the controls are disabled. Also, any messages the agent sends are no longer received by the user

**Comment by DylanCodeCabin** [comment]
This was fixed with the new chat system as we now have a restart chat feature instead of disabled controls.
