### ISSUE TITLE
Plugin Shows "0" visitors online if you delete departments

### ISSUE THREAD

**Issue by NathanM101** [CodeCabin/wp-live-chat-support#310]
If you add departments and delete them and leave the switch "User Department Selection" enabled, this causes the plugin to falter (break) looking for the departments. I have only tested on my Localhost, so this may need confirmation from other dev environments for replication. Another fix is to - 

- Turn the Chat agent off in the Users profile, and then turning it on again, fixes the problem. Again, this needs replication from someone else.

**Comment by JarekCodeCabin** [comment]
I tested this on localhost and online server (Chrome and Firefox) but couldn't replicate it

**Comment by DylanCodeCabin** [comment]
Closing
