### ISSUE TITLE
Chat box doesn't open up after being minimized when a new message comes through

### ISSUE THREAD

**Issue by JarrydLong** [CodeCabin/wp-live-chat-support#316]

**Comment by JarekCodeCabin** [comment]
When the chat box is minimized and new message comes small alert icon should show up. I'm not sure if chat box should open up either

**Comment by JarrydLong** [comment]
I've had a few clients request that it pops up again - perhaps we can make this an option in the settings page

**Comment by JarekCodeCabin** [comment]
I added settings that allows opening chat box when new message comes and chat box is minimized in this commit: https://github.com/CodeCabin/wp-live-chat-support/commit/6fcf0abb297c97b297b4f6efc1e435813768e0b7
When this option is disabled chat box will not open but small alert icon will show up

**Comment by DylanCodeCabin** [comment]
Correct, this was added and works perfectly
