### ISSUE TITLE
Compatibility issues with CloudFlare - Solution provided by client

### ISSUE THREAD

**Issue by JarrydLong** [CodeCabin/wp-live-chat-support#328]
>  WP LiveChat inserts a nonce in the HTML code sent to each website user. However, if the plugin creates a single HTML cache for all users (or if one uses CloudFlare's performance package and caches the HTML), then the plugin will fail to even initialize because the nonce inside the cached HTML only works for one user. We worked around this issue by modifying the code to insert the nonce in the HTML via AJAX and we set a timeout on the javascript which initializes the message box. However, a more elegant solution would be to load the nonce via AJAX and then trigger the message box initialization once that is done.

**Comment by DylanCodeCabin** [comment]
@NickDuncanZA Correct me if I am wrong, but if we loaded a security none over AJAX, would this not then also allow external sources -> Such as a potential attacker to simply request a nonce for use in the attack? 

Personally, I think we should stay away from this approach. We should rather be focusing on proper cache documentation, showing how to setup cache expiration to assist with issues such as this one.

**Comment by NickDuncanZA** [comment]
We use cloudflare on wp-livechat.com and the chat is working

**Comment by DylanCodeCabin** [comment]
Correct -> I am closing this now then
