### ISSUE TITLE
Plugin triggers a fatal error on activation

### ISSUE THREAD

**Issue by JarrydLong** [CodeCabin/wp-live-chat-support#329]
Error: 

Fatal error: Call to a member function add_cap() on null in […]/wp-content/plugins/wp-live-chat-support/wp-live-chat-support.php on line 3147

Configuration/Setup:

- WordPress version is 4.7.5
- WP Live Chat Support plugin version 7.0.07.
- PHP version is 5.6

**Comment by JarrydLong** [comment]
Forum topic: https://wordpress.org/support/topic/plugin-activation-failure-3/

**Comment by JarekCodeCabin** [comment]
I tested this with setup: 

* WordPress version is 4.7.5
* WP Live Chat Support plugin version 7.0.07.
* PHP version is 5.6.25
and couldn't replicate it.

The quick workaround would be replacing 3147 line with this:
`if( $admins !== null ) {
  $admins->add_cap('wplc_ma_agent');
}`

**Comment by NickDuncanZA** [comment]
Changed in two places:

Once in the `wplc_version_control();` function and once in the `wplc_activate();` function
