### ISSUE TITLE
Fails to load some assets when SSL is being used.

### ISSUE THREAD

**Issue by dylandrake616** [CodeCabin/wp-live-chat-support#332]
The plugin fails to load some assets if SSL is enabled in WP admin, as the code is getting the siteurl from the "get_option('siteurl')" function which doesn't take into consideration SSL on the admin side.

Switching that function to the "site_url()" fixes it.

**Comment by NickDuncanZA** [comment]
I have updated all `get_option('siteurl');` calls to `site_url();` except for the calls to the Cloud Server as this will cause duplicate domains being listed and a bunch of support tickets from confused people..
