### ISSUE TITLE
Chat box display wrong month number

### ISSUE THREAD

**Issue by JarekCodeCabin** [CodeCabin/wp-live-chat-support#352]
Instead of 7 as July it displays 6 so the date is 6/7, not 7/7.
This line should be changed:

`dateTime = dateTime.getMonth() + '/' + dateTime.getDate();`

to this:

`dateTime = (dateTime.getMonth() + 1) + '/' + dateTime.getDate();`

**Comment by DylanCodeCabin** [comment]
This was rebuilt to make use of a 'pretty print' date alternative. I think this should be safe to close now.
