### ISSUE TITLE
XSS Vulnerability via chat.

### ISSUE THREAD

**Issue by omaidf** [CodeCabin/wp-live-chat-support#358]
Sending either of the following messages via chat executes unwanted JavaScript in the receivers chat window:

`<img src=http://www.google.fr/images/srpr/logo3w.png onload=alert(this.ownerDocument.cookie) width=0 height= 0 />`

`x”</title><img src%3dx onerror%3dalert(1)>`

If you're having trouble reproducing, you can try sending these through Burp Suite which should do the trick as the payload needs to be encoded.

**Comment by ethicalhack3r** [comment]
Ryan from wpvulndb.com here. I was wondering if this issue has been patched?

**Comment by DylanCodeCabin** [comment]
Thank you so much for reporting this issue, we do appreciate your contribution. 

We are looking into this at the moment, and will do our best to get a patch ready as soon as possible from our side.

**Comment by NickDuncanZA** [comment]
Omaid, please get in touch with me on nick [@] codecabin . co . za

**Comment by NickDuncanZA** [comment]
@ethicalhack3r the patch will be going up today
