### ISSUE TITLE
Fix blurry agent avatar inside chat header

### ISSUE THREAD

**Issue by JarekCodeCabin** [CodeCabin/wp-live-chat-support#360]
Avatar is loaded from gravatar with size parameter set to 40px but css style is set to 60px.

It requires one change in modern.js file:

`html: '<img class="img-thumbnail img-circle wplc_thumb32 wplc_agent_involved" style="max-width:inherit;" id="agent_grav_'+taid+'" title="'+tname+'" src="'+timageurl+'?s=40" /><br /><span class="wplc_agent_name wplc-color-2">'+tname+'</span>'+ta_tagline+ta_bio`

to this:

`html: '<img class="img-thumbnail img-circle wplc_thumb32 wplc_agent_involved" style="max-width:inherit;" id="agent_grav_'+taid+'" title="'+tname+'" src="'+timageurl+'?s=60" /><br /><span class="wplc_agent_name wplc-color-2">'+tname+'</span>'+ta_tagline+ta_bio`

**Comment by DylanCodeCabin** [comment]
Complete in dev branch
