### ISSUE TITLE
Error: "Warning: Cannot assign an empty string to a string offset in /wp-includes/class.wp-scripts.php on line 447"

### ISSUE THREAD

**Issue by dylank6169** [CodeCabin/wp-live-chat-support#371]
Activating WP Live Chat Support on some sites causes a "Warning: Cannot assign an empty string to a string offset in /wp-includes/class.wp-scripts.php on line 447" PHP error on their site.

**Comment by PerryRylance** [comment]
This is a new warning in PHP 7

Please see here for more information https://bugs.php.net/bug.php?id=71572

**Comment by PerryRylance** [comment]
See here for solution https://github.com/CodeCabin/wp-live-chat-support/issues/373
