### ISSUE TITLE
Cannot assign empty string to string offset - WP 4.9, PHP 7.1

### ISSUE THREAD

**Issue by geig3r** [CodeCabin/wp-live-chat-support#373]
Corretion:

https://github.com/CodeCabin/wp-live-chat-support/blob/171537b8345eca1ef74eac5f87d94e57d801186b/wp-live-chat-support.php#L1246

Setting gravitar image = ""; is causing the problem when it is sent to the localize function.

**Comment by NickDuncanZA** [comment]
Thank you for this @geig3r 
The new version now has this implemented

**Comment by malela** [comment]
i replaced 
`$l10n[$key] = html_entity_decode( (string) $value, ENT_QUOTES, 'UTF-8');`
with this:
`if (!empty($value)) { $l10n[$key] = html_entity_decode( (string) $value, ENT_QUOTES, 'UTF-8'); }`
