### ISSUE TITLE
[WPLC V8] After clicking minimize icon and open it again, chat box goes off (Classic theme)

### ISSUE THREAD

**Issue by lpq66** [CodeCabin/wp-live-chat-support#380]
![wplc_v8b](https://user-images.githubusercontent.com/5943729/33667979-05096028-da64-11e7-9d25-c00ffdb10948.png)

**Comment by DylanCodeCabin** [comment]
We believe this issue has been resolved. Closing topic for the time being. 

This has been tested in our latest dev branch. Scheduled for release in the next few days.
