### ISSUE TITLE
[WPLC V8] After chat initiated chat box is not centered (Modern theme - chat box alignment: bottom left)

### ISSUE THREAD

**Issue by lpq66** [CodeCabin/wp-live-chat-support#382]
I also include the initiation chat box, just to see difference.
![wplc_v8b3](https://user-images.githubusercontent.com/5943729/33668422-4cdc3a78-da65-11e7-975d-4dfdb15d8fdb.png)

**Comment by NickDuncanZA** [comment]
Will be patched in the next version
Thank you Walter!
