### ISSUE TITLE
New NL (Dutch/Flemish) Translation submitted. 

### ISSUE THREAD

**Issue by DylanCodeCabin** [CodeCabin/wp-live-chat-support#383]
Fully completed translation (100%) has been submitted by (User prefers not to be credited) - This should be included in next release and credit given of course.
[wplivechat.zip](https://github.com/CodeCabin/wp-live-chat-support/files/1538000/wplivechat.zip)

**Comment by DylanCodeCabin** [comment]
User prefers not to be given credit - I have said that this is fine 👍

**Comment by NickDuncanZA** [comment]
Added in 080186ea914149e7f3479d939f026ea7b02db367
