### ISSUE TITLE
[WPLC V8] After chat is initiated, chat box off the screen (Modern theme - Chat box alignment: Right)

### ISSUE THREAD

**Issue by lpq66** [CodeCabin/wp-live-chat-support#384]
Happens only on iPhone 6 Plus (screen width 414px - 500px)
![wplc_v8b4](https://user-images.githubusercontent.com/5943729/33726200-fb6667ba-db39-11e7-91ec-92574262e45a.png)

**Comment by NickDuncanZA** [comment]
Will be patched in the next version
