### ISSUE TITLE
Surveys not working after chat

### ISSUE THREAD

**Issue by NickDuncanZA** [CodeCabin/wp-live-chat-support#385]
Possible SSL issues. Make sure all items are loaded via SSL now that nimblesquirrel now supports SSL

**Comment by DylanCodeCabin** [comment]
Does not seem to be an SSL issue. I am currently debugging this further to see where things are going wrong.

**Comment by DylanCodeCabin** [comment]
There was a missing event trigger for the node alternative. I have resolved this, and it should work moving forward.
