### ISSUE TITLE
GoDaddy Managed

### ISSUE THREAD

**Issue by NickDuncanZA** [CodeCabin/wp-live-chat-support#927]
GoDaddy Managed caching doesn't work with the mobile app. You have to flush their cache constantly to get through the device approval process and then again to get the app into online mode. Is it possible to build some sort of cache busting into this process? I don't see and can't find any info on how to exclude anything with their caching.

Reported by @andtrev

**Comment by NickDuncanZA** [comment]
We will need to assign timestamps to the endpoint of the API calls to avoid caching

**Comment by NickDuncanZA** [comment]
I'll work this into the 8.0.05 release (Wednesday)

**Comment by NickDuncanZA** [comment]
@DylanCodeCabin We will need to modify the App endpoints as well please

**Comment by DylanCodeCabin** [comment]
@NickDuncanZA If this is app only issue, I should be able to simply add a timestamp to the end of the queries. That should fix it then.

I will get a patch up today for the app.

**Comment by DylanCodeCabin** [comment]
I add the timestamp to the rest wrapper in the JS code as well (plugin side) to ensure this fixes all rest calls. Will add this in my PR for the visitor sound notification today.

**Comment by DylanCodeCabin** [comment]
This was added where needed -> Closing this now
