### ISSUE TITLE
Styling Issue - Width not set on Chat Box

### ISSUE THREAD

**Issue by VeroniqueSmit** [CodeCabin/wp-live-chat-support#940]

**Comment by NickDuncanZA** [comment]
Do you have any more details on this bug @VeroniqueSmit?

**Comment by DylanCodeCabin** [comment]
@VeroniqueSmit Is it safe for us to close this one off, I haven't been able to reproduce this one.

**Comment by DylanCodeCabin** [comment]
Going ahead and closing this off: `Not enough information to debug this one further`
