### ISSUE TITLE
WPLC Integration with Contact Form Ready - Form Does Not Display

### ISSUE THREAD

**Issue by patdumond** [CodeCabin/wp-live-chat-support#946]
WPLC version 8.0.07 and Contact Form Ready version 2.0.00. I've set up a form to be used with Offline Messages. When agents are offline, the proper message is displayed by WPLC but when I try to submit an offline message only the bar saying "Chat offline. Leave a message." is displayed. See screenshot.

![2018-03-27_9-40-33](https://user-images.githubusercontent.com/9320495/37974856-8e72ec76-31a3-11e8-8ed3-f90f2caa8848.png)

**Comment by DylanCodeCabin** [comment]
I thought we had patched this previously. It appears to be a conflict with the integration specifically.

We need to add this to resolve it, as we currently place it as a fixed item

`#wp-live-chat-inner .wpcf_wrapper {
    position: inherit;
    padding: 25px;
}
`

**Comment by NickDuncanZA** [comment]
Fixed in c2aa0c8
