### ISSUE TITLE
Test - remove the height from wplc_hovercard_content

### ISSUE THREAD

**Issue by NickDuncanZA** [CodeCabin/wp-live-chat-support#95]
The height should be automatic... test the following:

#wplc_hovercard_content {
    padding: 15px;
    /* height: 100px; */
    box-shadow: 0 1px 1px #f0f0f1;
    **display: block;
    overflow: auto;**
}

**Comment by NickDuncanZA** [comment]
remove the height from `wplc_hovercard_content_left` and `wplc_hovercard_content_right` as well

**Comment by DylanCodeCabin** [comment]
```
#wplc_hovercard{
  height: auto;
}
#wplc_hovercard_content {
 display:flex;
 height: auto;
}
#wplc_hovercard_content_left{
  height:auto;
}
#wplc_hovercard_content_right{
  height: auto;
}
```
