### ISSUE TITLE
Minimize issue

### ISSUE THREAD

**Issue by DylanCodeCabin** [CodeCabin/wp-live-chat-support#953]
In the modern.js the following line: 

` if (Cookies.get('wplc_minimize') === 'yes') { } else {`

Appears to be true for some users on page load. It does not seem to be affecting all users, but it is occurring. We need to investigate this further to determine when this cookie is being set incorrectly.

**Comment by andtrev** [comment]
I'm not sure if the cookie is set incorrectly, the chat box is minimized at that point, but when opened the minimize cookie doesn't get reset before that check, only gets resets to "" if it's already not minimized. I fixed this in this commit by checking if the active class is present, perhaps there's a better way: https://github.com/CodeCabin/wp-live-chat-support/pull/949/commits/c0d1cf17bc204a60f28d0d9e6dee993b18a357c6

**Comment by NickDuncanZA** [comment]
Looks like your fix worked @andtrev - no new reports of this issue
