### ISSUE TITLE
Warning Message

### ISSUE THREAD

**Issue by Drewstar** [CodeCabin/wp-live-chat-support#954]
Hi:

I have noticed this warning ever since I upgraded to Pro. By the way, I do have both plugins installed. The Support & Pro.

This message is in the upper left hand corner. It is only showing when I click the 'Live Chat' link on the left hand side in my WordPress Dashboard.

Dear Pro User,
Your API Key could not be validated, some functionality may be limited 

Thanks,
Drew

**Comment by NickDuncanZA** [comment]
Hi @Drewstar 
Thank you for this report. Did you have a valid API key inserted at that time?

**Comment by DylanCodeCabin** [comment]
Hi @Drewstar 

Just checking in again from our side, did you manage to get things setup on your side? 

We are eager to assist if possible.

**Comment by DylanCodeCabin** [comment]
Closing this issue now as we are unable to debug this without further feedback from the user who logged this.
