### ISSUE TITLE
Chat delay not respected when no cid is set

### ISSUE THREAD

**Issue by andtrev** [CodeCabin/wp-live-chat-support#957]
Chat delay doesn't work without a cid set in cookies, which means for first time visits and for visits with only the offline message display chat delay does not work and the chat bubble always pops up immediately.

**Comment by NickDuncanZA** [comment]
Bug confirmed with the basic version only
Looking at a fix now

**Comment by NickDuncanZA** [comment]
Cannot reproduce with the Pro version (8.0.07)
Please reconfirm this bug @andtrev
