### ISSUE TITLE
Update NL translations

### ISSUE THREAD

**Issue by PerryRylance** [CodeCabin/wp-live-chat-support#966]
[temp.zip](https://github.com/CodeCabin/wp-live-chat-support/files/2170261/temp.zip)

**Comment by NickDuncanZA** [comment]
Thanks @PerryRylance . Who do we have to thank for this? I'd like to credit them in the readme

**Comment by NickDuncanZA** [comment]
Added in d53668a8ccc2a8cd67574481b33be49cb9cedc56
