### ISSUE TITLE
No prompt to check GDPR checkbox

### ISSUE THREAD

**Issue by PerryRylance** [CodeCabin/wp-live-chat-support#971]
There should be a focus, highlight or animation when you try to start chat without pressing GDPR agreement. Currently it may give the impression that the start chat button doesn't do anything

**Comment by DylanCodeCabin** [comment]
I am marking this as a bug as it is a UX bug in my opinion, and will drastically improve the way things are handled in the GDPR compliance module.

**Comment by DylanCodeCabin** [comment]
![image](https://user-images.githubusercontent.com/16894783/42809074-fc78062a-89b4-11e8-9a96-9ad645a73686.png)

We now have this very subtle border which will show up in a dark red if the checkbox is not ticket. Simple add/remove class system. Nothing over bearing or time consuming.
