### ISSUE TITLE
Update Bulgarian Translation File

### ISSUE THREAD

**Issue by StevenDeBeer** [CodeCabin/wp-live-chat-support#976]
[nd_r_BkO_9RO7Q-wplivechat-bg_BG.po.zip](https://github.com/CodeCabin/wp-live-chat-support/files/2196925/nd_r_BkO_9RO7Q-wplivechat-bg_BG.po.zip)

Ticket ID: BkyRgFJXm

Credit: Emil Genchev

**Comment by DylanCodeCabin** [comment]
Interestingly we did not have Bulgarian previously. This is now added in the dev branch, and credit has been given
