### ISSUE TITLE
Chat sometimes still switched on following refresh

### ISSUE THREAD

**Issue by PerryRylance** [CodeCabin/wp-live-chat-support#991]
Steps:

- Start chatting
- End chatting
- Refresh page

Expected behaviour:
- Button is red following refresh

Observed behaviour
- Button is still green, chat is still on following refresh

This doesn't always happen, and can sometimes happen even after waiting quite some time for the "close chat" AJAX request to complete.

**Comment by DylanCodeCabin** [comment]
I believe this should no longer be an issue in the upcoming release as there was an issue with switching online.
