### ISSUE TITLE
Fix responsive styling

### ISSUE THREAD

**Issue by StevenDeBeer** [CodeCabin/wp-live-chat-support#993]
On some devices the chat header bubble becomes un-clickable as it is behind the chat box itself.

The following CSS resolves the issue:
```
@media screen and (max-width:510px){
#wp-live-chat-2,
#wp-live-chat-4 {
bottom:100px;
}
}
```

**Comment by DylanCodeCabin** [comment]
Complete: Due for release in 8.0.15
