### ISSUE TITLE
Google Tag - Event Tracking

### ISSUE THREAD

**Issue by NickDuncanZA** [CodeCabin/wp-live-chat-support#995]
We need to add support for the new versions of the Google Analytics tracking codes so that event tracking still works.

**Comment by andtrev** [comment]
I believe our Google tracking is correct, I've seen issues where some analytics plugins rename the tracker to something other than ga. That'll break our event tracking and the user will have to add some Javascript to to fix that.

So if the analytics plugin renames the tracker to _gaTracker then you'd want to put this js in the custom scripts:

__gaTracker( function() {
  window.ga = __gaTracker;
});

Than our code will be able to track events.

**Comment by DylanCodeCabin** [comment]
@NickDuncanZA Are you happy for me to close this based on the info provided by @andtrev ?
